// <auto-generated />
using System;
using Ace.Geograpi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ace.Geograpi.Infrastructure.Migrations
{
    [DbContext(typeof(GeograpiDbContext))]
    [Migration("20240504220958_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ace.Geograpi.Infrastructure.Data.Entities.ContinentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("continents", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Africa",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Antarctica",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Asia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Australia (Oceania)",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Europe",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "North America",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "South America",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("Ace.Geograpi.Infrastructure.Data.Entities.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContinentId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("countries", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Afghanistan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Albania",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Algeria",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Andorra",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Angola",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Antigua and Barbuda",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Argentina",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Armenia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Australia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 10,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Austria",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Azerbaijan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 12,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bahamas",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 13,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bahrain",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 14,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bangladesh",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 15,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Barbados",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 16,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Belarus",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 17,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Belgium",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 18,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Belize",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 19,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Benin",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 20,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bhutan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 21,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bolivia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 22,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bosnia and Herzegovina",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 23,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Botswana",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 24,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Brazil",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 25,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Brunei",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 26,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Bulgaria",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 27,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Burkina Faso",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 28,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Burundi",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 29,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Cabo Verde",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 30,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Cambodia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 31,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Cameroon",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 32,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Canada",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 33,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Central African Republic",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 34,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Chad",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 35,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Chile",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 36,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "China",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 37,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Colombia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 38,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Comoros",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 39,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Congo, Democratic Republic of the",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 40,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Congo, Republic of the",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 41,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Costa Rica",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 42,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Cote d'Ivoire",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 43,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Croatia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 44,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Cuba",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 45,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Cyprus",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 46,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Czech Republic",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 47,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Denmark",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 48,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Djibouti",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 49,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Dominica",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 50,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Dominican Republic",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 51,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "East Timor (Timor-Leste)",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 52,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ecuador",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 53,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Egypt",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 54,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "El Salvador",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 55,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Equatorial Guinea",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 56,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Eritrea",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 57,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Estonia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 58,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Eswatini",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 59,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ethiopia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 60,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Fiji",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 61,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Finland",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 62,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "France",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 63,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Gabon",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 64,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Gambia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 65,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Georgia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 66,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Germany",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 67,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ghana",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 68,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Greece",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 69,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Grenada",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 70,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Guatemala",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 71,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Guinea",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 72,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Guinea-Bissau",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 73,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Guyana",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 74,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Haiti",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 75,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Honduras",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 76,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Hungary",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 77,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Iceland",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 78,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "India",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 79,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Indonesia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 80,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Iran",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 81,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Iraq",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 82,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ireland",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 83,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Israel",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 84,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Italy",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 85,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Jamaica",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 86,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Japan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 87,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Jordan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 88,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kazakhstan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 89,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kenya",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 90,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kiribati",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 91,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Korea, North",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 92,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Korea, South",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 93,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kosovo",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 94,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kuwait",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 95,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Kyrgyzstan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 96,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Laos",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 97,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Latvia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 98,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Lebanon",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 99,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Lesotho",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 100,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Liberia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 101,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Libya",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 102,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Liechtenstein",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 103,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Lithuania",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 104,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Luxembourg",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 105,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Madagascar",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 106,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Malawi",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 107,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Malaysia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 108,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Maldives",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 109,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Mali",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 110,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Malta",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 111,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Marshall Islands",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 112,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Mauritania",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 113,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Mauritius",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 114,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Mexico",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 115,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Micronesia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 116,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Moldova",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 117,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Monaco",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 118,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Mongolia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 119,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Montenegro",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 120,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Morocco",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 121,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Mozambique",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 122,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Myanmar (Burma)",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 123,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Namibia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 124,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Nauru",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 125,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Nepal",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 126,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Netherlands",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 127,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "New Zealand",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 128,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Nicaragua",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 129,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Niger",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 130,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Nigeria",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 131,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "North Macedonia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 132,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Norway",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 133,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Oman",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 134,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Pakistan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 135,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Palau",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 136,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Panama",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 137,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Papua New Guinea",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 138,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Paraguay",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 139,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Peru",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 140,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Philippines",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 141,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Poland",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 142,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Portugal",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 143,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Qatar",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 144,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Romania",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 145,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Russia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 146,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Rwanda",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 147,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Saint Kitts and Nevis",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 148,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Saint Lucia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 149,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Saint Vincent and the Grenadines",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 150,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Samoa",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 151,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "San Marino",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 152,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Sao Tome and Principe",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 153,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Saudi Arabia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 154,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Senegal",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 155,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Serbia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 156,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Seychelles",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 157,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Sierra Leone",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 158,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Singapore",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 159,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Slovakia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 160,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Slovenia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 161,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Solomon Islands",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 162,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Somalia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 163,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "South Africa",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 164,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Spain",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 165,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Sri Lanka",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 166,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Sudan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 167,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Sudan, South",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 168,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Suriname",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 169,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Sweden",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 170,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Switzerland",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 171,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Syria",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 172,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Taiwan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 173,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Tajikistan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 174,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Tanzania",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 175,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Thailand",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 176,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Togo",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 177,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Tonga",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 178,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Trinidad and Tobago",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 179,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Tunisia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 180,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Turkey",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 181,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Turkmenistan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 182,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Tuvalu",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 183,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Uganda",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 184,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Ukraine",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 185,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "United Arab Emirates",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 186,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "United Kingdom",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 187,
                            ContinentId = 6,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "United States",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 188,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Uruguay",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 189,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Uzbekistan",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 190,
                            ContinentId = 4,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Vanuatu",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 191,
                            ContinentId = 5,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Vatican City",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 192,
                            ContinentId = 7,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Venezuela",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 193,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Vietnam",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 194,
                            ContinentId = 3,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Yemen",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 195,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Zambia",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 196,
                            ContinentId = 1,
                            CreatedBy = 0,
                            DeletedBy = 0,
                            IsDeleted = false,
                            Name = "Zimbabwe",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("Ace.Geograpi.Infrastructure.Data.Entities.CountryEntity", b =>
                {
                    b.HasOne("Ace.Geograpi.Infrastructure.Data.Entities.ContinentEntity", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Ace.Geograpi.Infrastructure.Data.Entities.ContinentEntity", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
