@uri={{scheme}}://{{hostname}}:{{port}}

@id=5
@tempId=999


GET {{uri}}/api/v1/continents
###
GET {{uri}}/api/v1/continents?page=1&size=3
###
GET {{uri}}/api/v1/continents?sortBy=Name&sortDirection=Descending
###
GET {{uri}}/api/v1/continents?name=Europe
###
GET {{uri}}/api/v1/continents?ids=1&ids=2&ids=3

###

GET {{uri}}/api/v1/continents/count
###
GET {{uri}}/api/v1/continents/count?ids=1&ids=2&ids=3
###
GET {{uri}}/api/v1/continents/count?name=Europe

###

GET {{uri}}/api/v1/continents/{{id}}

###

POST {{uri}}/api/v1/continents
Content-Type: application/json

{
    "name": "Foo"
}

###

PUT {{uri}}/api/v1/continents/{{tempId}}
Content-Type: application/json

{
    "id": {{tempId}},
    "name": "Bar"
}

###

DELETE {{uri}}/api/v1/continents/{{tempId}}
