@uri={{scheme}}://{{hostname}}:{{port}}

@id=144
@tempId=??

###

GET {{uri}}/api/v1/countries
###
GET {{uri}}/api/v1/countries?page=1&size=3
###
GET {{uri}}/api/v1/countries?sortBy=Name&sortDirection=Descending
###
GET {{uri}}/api/v1/countries?name=Romania
###
GET {{uri}}/api/v1/countries?ids=1&ids=2&ids=3

###

GET {{uri}}/api/v1/countries/count
###
GET {{uri}}/api/v1/countries/count?ids=1&ids=2&ids=3
###
GET {{uri}}/api/v1/countries/count?name=Romania

###

GET {{uri}}/api/v1/countries/{{id}}

###

POST {{uri}}/api/v1/countries
Content-Type: application/json

{
    "continentId": 1
    "name": "Foo",
}

###

PUT {{uri}}/api/v1/countries/{{tempId}}
Content-Type: application/json

{
    "id": {{tempId}},
    "continentId": 1,
    "name": "Bar"
}

###

DELETE {{uri}}/api/v1/countries/{{tempId}}
