version: '3.4'

services:
  ace.geograpi.api:
    image: ${DOCKER_REGISTRY-}acegeograpiweb
    container_name: ace.geograpi.api
    restart: always
    build:
      context: .
      dockerfile: Ace.Geograpi.Web/Dockerfile
    depends_on:
      - "ace.geograpi.db"
      - "ace.geograpi.mq"
    ports:
      - 42000:443
      - 43000:80
    volumes:
      - ./.containers/ace-geograpi-api-logs:/app/Logs

  ace.geograpi.db:
    image: postgres:latest
    container_name: ace.geograpi.db
    restart: always
    environment:
      - POSTGRES_DB=geograpi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.containers/ace-geograpi-db:/var/lib/postgresql/data

  ace.geograpi.mq:
    image: rabbitmq:4-management-alpine
    container_name: ace.geograpi.mq
    hostname: ace.geograpi.rabbitmq
    depends_on:
      - "ace.geograpi.db"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.containers/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.containers/rabbitmq/log/:/var/log/rabbitmq

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    restart: always
    depends_on:
      - "ace.geograpi.db"
      - "ace.geograpi.api"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@geograpi.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    volumes:
      - ./.containers/pg-admin:/var/lib/pgadmin
