version: '3.4'

services:
  ace.geograpi.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=42000
      - ASPNETCORE_HTTP_PORTS=43000
    ports:
      - "42000:42000"
      - "43000:43000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
