version: '3.4'

services:
  ace.geograpi.api:
    image: ${DOCKER_REGISTRY-}acegeograpiweb
    container_name: ace.geograpi.api
    restart: always
    build:
      context: .
      dockerfile: Ace.Geograpi.Web/Dockerfile
    depends_on:
      - ace.geograpi.db
    ports:
      - 42000:443
      - 43000:80

  ace.geograpi.db:
    image: postgres:latest
    container_name: ace.geograpi.db
    restart: always
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    restart: always
    depends_on:
      - ace.geograpi.db
    ports:
      - 5050:80
