name: build-CI

on:
  push:
    branches:
    - ace
    - main
    - develop
    - feature/**
    - bugfix/**
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  build:

    env:
      CONFIG: 'Release'
      SOLUTION: 'src/Ace.Geograpi.sln'
      TEST_PROJECT_ARCHITECTURE: 'src\tests\Ace.Geograpi.ArchitectureTests/Ace.Geograpi.ArchitectureTests.csproj'
      TEST_PROJECT_APPLICATION: 'src\tests\Ace.Geograpi.Application.Tests/Ace.Geograpi.Application.Tests.csproj'
      TEST_PROJECT_INFRASTRUCTURE: 'src\tests\Ace.Geograpi.Infrastructure.IntegrationTests/Ace.Geograpi.Infrastructure.IntegrationTests.csproj'
      TEST_PROJECT_WEB_INTEGRATION: 'src\tests\Ace.Geograpi.Web.IntegrationTests/Ace.Geograpi.Web.IntegrationTests.csproj'
      TEST_PROJECT_WEB: 'src\tests\Ace.Geograpi.Web.Tests/Ace.Geograpi.Web.Tests.csproj'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        cache: true
        cache-dependency-path: '**/*.csproj'

    - name: dotnet restore
      run: dotnet restore $SOLUTION

    - name: dotnet build
      run: dotnet build $SOLUTION --configuration $CONFIG --no-restore

    - name: dotnet test > architecture tests
      run: dotnet test $TEST_PROJECT_ARCHITECTURE --configuration $CONFIG --no-restore --no-build --verbosity normal

    - name: dotnet test > application unit tests
      run: dotnet test $TEST_PROJECT_APPLICATION --configuration $CONFIG --no-restore --no-build --verbosity normal

    - name: dotnet test > infrastructure integration tests
      run: dotnet test $TEST_PROJECT_INFRASTRUCTURE --configuration $CONFIG --no-restore --no-build --verbosity normal

    - name: dotnet test > web integration tests
      run: dotnet test $TEST_PROJECT_WEB_INTEGRATION --configuration $CONFIG --no-restore --no-build --verbosity normal

    - name: dotnet test > web unit tests
      run: dotnet test $TEST_PROJECT_WEB --configuration $CONFIG --no-restore --no-build --verbosity normal
